import { Product } from "@/components/screen/accessories/column";

export const mockAccessories: Product[] = [
  {
    id: "A-001",
    name: "Mouse Pad RGB Gaming",
    category: "Phụ kiện gaming",
    brand: "Corsair",
    price: 890000,
    stock: 25,
    createdAt: new Date("2024-01-10").toISOString(),
  },
  {
    id: "A-002",
    name: "Webcam 4K Pro",
    category: "Webcam",
    brand: "Logitech",
    price: 3490000,
    stock: 12,
    createdAt: new Date("2024-02-05").toISOString(),
  },
  {
    id: "A-003",
    name: "USB Hub 7 Port",
    category: "Hub USB",
    brand: "Anker",
    price: 1290000,
    stock: 18,
    createdAt: new Date("2024-01-25").toISOString(),
  },
  {
    id: "A-004",
    name: "Wireless Charger Stand",
    category: "Sạc không dây",
    brand: "Samsung",
    price: 890000,
    stock: 30,
    createdAt: new Date("2024-03-12").toISOString(),
  },
  {
    id: "A-005",
    name: "Gaming Headset Stand",
    category: "Phụ kiện gaming",
    brand: "Razer",
    price: 690000,
    stock: 8,
    createdAt: new Date("2024-02-18").toISOString(),
  },
  {
    id: "A-006",
    name: "Cable Management Kit",
    category: "Dây cáp",
    brand: "IKEA",
    price: 290000,
    stock: 45,
    createdAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "A-007",
    name: "Monitor Arm Dual",
    category: "Giá đỡ màn hình",
    brand: "Dell",
    price: 2890000,
    stock: 6,
    createdAt: new Date("2024-01-30").toISOString(),
  },
  {
    id: "A-008",
    name: "Laptop Cooling Pad",
    category: "Tản nhiệt",
    brand: "Cooler Master",
    price: 1490000,
    stock: 15,
    createdAt: new Date("2024-02-20").toISOString(),
  },
  {
    id: "A-009",
    name: "Bluetooth Speaker Mini",
    category: "Loa",
    brand: "JBL",
    price: 2290000,
    stock: 20,
    createdAt: new Date("2024-03-05").toISOString(),
  },
  {
    id: "A-010",
    name: "Power Bank 20000mAh",
    category: "Pin dự phòng",
    brand: "Xiaomi",
    price: 890000,
    stock: 35,
    createdAt: new Date("2024-01-15").toISOString(),
  },
];
