import { Order } from "@/components/screen/order/column";

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    customerName: "Nguyễn Văn A",
    customerEmail: "nguyenvana@gmail.com",
    status: "pending",
    totalAmount: 2890000,
    orderDate: new Date("2024-06-20").toISOString(),
    items: [
      { name: "Cherry MX Red", quantity: 2, price: 890000 },
      { name: "OEM Black PBT", quantity: 1, price: 590000 },
    ],
  },
  {
    id: "ORD-002",
    customerName: "Trần Thị B",
    customerEmail: "tranthib@gmail.com",
    status: "completed",
    totalAmount: 1490000,
    orderDate: new Date("2024-06-18").toISOString(),
    items: [
      { name: "Gateron Yellow", quantity: 1, price: 590000 },
      { name: "Laptop Cooling Pad", quantity: 1, price: 1490000 },
    ],
  },
  {
    id: "ORD-003",
    customerName: "Lê Minh C",
    customerEmail: "leminhc@gmail.com",
    status: "shipped",
    totalAmount: 4580000,
    orderDate: new Date("2024-06-22").toISOString(),
    items: [
      { name: "GMK Olivia", quantity: 1, price: 2990000 },
      { name: "Holy Panda", quantity: 1, price: 1490000 },
    ],
  },
  {
    id: "ORD-004",
    customerName: "Phạm Quang D",
    customerEmail: "phamquangd@gmail.com",
    status: "cancelled",
    totalAmount: 1190000,
    orderDate: new Date("2024-06-15").toISOString(),
    items: [{ name: "Alpaca V2", quantity: 1, price: 1190000 }],
  },
  {
    id: "ORD-005",
    customerName: "Hoàng Thị E",
    customerEmail: "hoangthie@gmail.com",
    status: "pending",
    totalAmount: 3280000,
    orderDate: new Date("2024-06-25").toISOString(),
    items: [
      { name: "SA Miami Nights", quantity: 1, price: 2490000 },
      { name: "Tai-Hao Cubic", quantity: 1, price: 790000 },
    ],
  },
  {
    id: "ORD-006",
    customerName: "Vũ Đức F",
    customerEmail: "vuducf@gmail.com",
    status: "completed",
    totalAmount: 2480000,
    orderDate: new Date("2024-06-19").toISOString(),
    items: [
      { name: "Cherry Profile White", quantity: 1, price: 1990000 },
      { name: "Gaming Headset Stand", quantity: 1, price: 690000 },
    ],
  },
  {
    id: "ORD-007",
    customerName: "Đặng Thu G",
    customerEmail: "dangthug@gmail.com",
    status: "shipped",
    totalAmount: 1780000,
    orderDate: new Date("2024-06-23").toISOString(),
    items: [{ name: "DSA Granite", quantity: 1, price: 1790000 }],
  },
  {
    id: "ORD-008",
    customerName: "Bùi Văn H",
    customerEmail: "buivanh@gmail.com",
    status: "pending",
    totalAmount: 2080000,
    orderDate: new Date("2024-06-26").toISOString(),
    items: [
      { name: "Tangerine 67g", quantity: 1, price: 1390000 },
      { name: "Kailh Box Jade", quantity: 1, price: 690000 },
    ],
  },
  {
    id: "ORD-009",
    customerName: "Ngô Thị I",
    customerEmail: "ngothii@gmail.com",
    status: "completed",
    totalAmount: 1880000,
    orderDate: new Date("2024-06-17").toISOString(),
    items: [{ name: "Power Bank 20000mAh", quantity: 2, price: 890000 }],
  },
  {
    id: "ORD-010",
    customerName: "Lý Quốc J",
    customerEmail: "lyquocj@gmail.com",
    status: "shipped",
    totalAmount: 1990000,
    orderDate: new Date("2024-06-24").toISOString(),
    items: [
      { name: "MT3 Susuwatari", quantity: 1, price: 1590000 },
      { name: "Cable Management Kit", quantity: 1, price: 290000 },
    ],
  },
];
