import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "@/components/providers/query-client-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Background from "@/components/organisms/background";

const inter = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Core App",
  description: "Generated by Core App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <ReactQueryProviders>
          <Background />
          <ThemeProvider>{children}</ThemeProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
